name: Python Run Check

on: 
  push:
    paths:
      - 'main.py'
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip3 install obs-websocket-py pytest

    - name: Create config.json
      run: |
        cat << EOF > config.json
        {
          "meta": {
            "ctime": {
              "by": "${{ github.actor }}",
              "at": $(date +%s)
            }
          },
          "locale": {
            "lang": "en",
            "en": {
              "scene-list": "Scene List",
              "scene-name": "Scene Name",
              "source-list": "Source List",
              "source-name": "Source Name"
            },
            "ja": {
              "scene-list": "シーン一覧",
              "scene-name": "シーン名",
              "source-list": "ソース一覧",
              "source-name": "ソース名"
            }
          },
          "connect": {
            "host": "localhost",
            "port": 4455,
            "password": "password"
          },
          "SaveSourceScreenshot": {
            "imageFormat": "webp",
            "imageFilePath": "/home/runner/work/obswebsocket_screenshot/obswebsocket_screenshot/Screenshot_${source_name}_${time}.webp"
          }
        }
        EOF

    - name: run main.py
      run: python3 main.py || echo "Skipped or Failed"

    - name: Upload log file
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-log
        path: outputlog(latest).log
