name: Python Package using Conda

on: 
  push:
    paths:
      - 'main.py'
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: pip3 install obs-websocket-py pytest
    - name: run main.py
      run: pytest main.py
